<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZXxUP6w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZXxUP6w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZXxUP6w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZXxUP6w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZXxUP6w\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZXxUP6w',
    'container.build_id' => '2fee76c9',
    'container.build_time' => 1627372303,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZXxUP6w');
