<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6r5NUJR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6r5NUJR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6r5NUJR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6r5NUJR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6r5NUJR\App_KernelDevDebugContainer([
    'container.build_hash' => '6r5NUJR',
    'container.build_id' => 'cbcbaffb',
    'container.build_time' => 1626791026,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6r5NUJR');
